export { default as HomeScreen } from './HomeScreen'
export { default as LoginScreen } from './LoginScreen'
export { default as RegistrationScreen} from './RegistrationScreen'
export { default as ClassesScreen } from './ClassesScreen'
export { default as ProfileScreen } from './ProfileScreen'